version: '3.8'

services:
  api-server:
    image: ghcr.io/dahao-04/chatapp/api-server:latest 
    
    environment:
      - DB_URL=${DB_URL}         
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_REFRESH_KEY=${SECRET_REFRESH_KEY}
      
    container_name: api-server
    restart: always
    
  chat-server:
    image: ghcr.io/dahao-04/chatapp/chat-server:latest
    environment:
      - SECRET_KEY=${SECRET_KEY}
    container_name: chat-server
    restart: always
    depends_on:
      - api-server

  client:
    image: ghcr.io/dahao-04/chatapp/client:latest
    container_name: client
    restart: always
    depends_on:
      - api-server
      - chat-server

  nginx-gateway:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/ssl/cloudflare:/etc/nginx/ssl:ro
    depends_on:
      - client
    restart: always